FROM golang:1.18 AS building

COPY . /building
WORKDIR /building

RUN make frps

FROM alpine:3.15

COPY --from=building /building/bin/frps /usr/bin/frps
COPY --from=building /building/conf/frps_full.ini /conf/frps_full.ini
RUN mkdir -p /data/log
CMD ["/usr/bin/frps", "-c", "/conf/frps_full.ini"]
