FROM golang:1.20 AS building

COPY . /building
WORKDIR /building

RUN make frpc

FROM alpine:3

COPY --from=building /building/bin/frpc /usr/bin/frpc
COPY --from=building /building/conf/frpc.ini /conf/frpc.ini

CMD ["/usr/bin/frpc","","-c","/conf/frpc.ini"]
