FROM golang:1.18 AS building

COPY . /building
WORKDIR /building

RUN make frpc

FROM alpine:3.15

COPY --from=building /building/bin/frpc /usr/bin/frpc
COPY --from=building /building/conf/frpc_full.ini /conf/frpc_full.ini

CMD ["/usr/bin/frpc","","-c","/conf/frpc_full.ini"]
